version: "3.3"
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:2.5.2
    hostname: starrocks-fe
    container_name: starrocks-fe
    user: root
    command: /opt/starrocks/fe/bin/start_fe.sh --host_type FQDN
    ports:
      - 1030:8030
      - 2020:9020
      - 3030:9030
    volumes:
#      - ../../conf/fe.conf:/opt/starrocks/fe/conf/fe.conf
      - ./starrocks/fe/meta:/opt/starrocks/fe/meta
      - ./starrocks/fe/log:/opt/starrocks/fe/log

  starrocks-be1:
    image: starrocks/be-ubuntu:2.5.2
    user: root
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be1:9050\";"
        /opt/starrocks/be/bin/start_be.sh 

    hostname: starrocks-be1
    container_name: starrocks-be1
    depends_on:
      - "starrocks-fe"
    volumes:
#      - - ../../conf/be.conf:/opt/starrocks/be/conf/be.conf
      - ./starrocks/starrocks-be1/storage:/opt/starrocks/be/storage
      - ./starrocks/starrocks-be1/log:/opt/starrocks/be/log
  starrocks-be2:
    image: starrocks/be-ubuntu:2.5.2
    user: root
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s;  mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be2:9050\";"
        /opt/starrocks/be/bin/start_be.sh 

    hostname: starrocks-be2
    container_name: starrocks-be2
    depends_on:
      - "starrocks-fe"
    volumes:
#      - ../../conf/be.conf:/opt/starrocks/be/conf/be.conf
      - ./starrocks/starrocks-be2/storage:/opt/starrocks/be/storage
      - ./starrocks/starrocks-be2/log:/opt/starrocks/be/log
  starrocks-be3:
    image: starrocks/be-ubuntu:2.5.2
    user: root
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be3:9050\";"
        /opt/starrocks/be/bin/start_be.sh 

    hostname: starrocks-be3
    container_name: starrocks-be3
    depends_on:
      - "starrocks-fe"
    volumes:
#      - ../../conf/be.conf:/opt/starrocks/be/conf/be.conf
      - ./starrocks/starrocks-be3/storage:/opt/starrocks/be/storage
      - ./starrocks/starrocks-be3/log:/opt/starrocks/be/log