version: "3.3"
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:2.5.2
    hostname: starrocks-fe
    container_name: starrocks-fe
    user: root
    command:
      /opt/starrocks/fe/bin/start_fe.sh
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    healthcheck:
      test: 'mysql -uroot -h10.5.0.2 -P 9030 -e "show frontends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
#      - fe.conf:/opt/starrocks/fe/conf/fe.conf
      - ./starrocks/starrocks-fe/meta:/opt/starrocks/fe/meta
      - ./starrocks/starrocks-fe/log:/opt/starrocks/fe/log
    networks:
      network:
        ipv4_address: 10.5.0.2

  starrocks-be:
    image: starrocks/be-ubuntu:2.5.2
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"
        /opt/starrocks/be/bin/start_be.sh
    ports:
      - 8040:8040
    hostname: starrocks-be
    container_name: starrocks-be
    user: root
    depends_on:
      - starrocks-fe
    healthcheck:
      test: 'mysql -uroot -h10.5.0.2 -P 9030 -e "show backends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
#      - be.conf:/opt/starrocks/be/conf/be.conf
      - ./starrocks/starrocks-be/storage:/opt/starrocks/be/storage
      - ./starrocks/starrocks-be/log:/opt/starrocks/be/log
    networks:
      network:
        ipv4_address: 10.5.0.3
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
